substitutions:
  _REGION: us-central1
  _SERVICE: healthguard-frontend
  _VITE_API_URL: https://healthguard-backend-808293038514.us-central1.run.app

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - VITE_API_URL=${_VITE_API_URL}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/healthguard/${_SERVICE}:$BUILD_ID
      - ./frontend

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/healthguard/${_SERVICE}:$BUILD_ID

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/healthguard/${_SERVICE}:$BUILD_ID
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --port
      - "8080"

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/healthguard/${_SERVICE}:$BUILD_ID
